openapi: 3.0.0
info:
  title: Emarsys Loyalty API
  version: 1.0.0

servers:
  - url: https://contact-api.loyalsys.io/api/v4


paths:
  # Resource - Contact
  # Delete Contact
  /contact/:
    $ref: 'functions/deleteContact.yaml'

  # Add Contact
  /contact/join:
    $ref: 'functions/addContact.yaml'

  # Get Contact Loyalty Info
  /contact/contact:
    $ref: 'functions/getContactLoyaltyInfo.yaml'

  # Get Contact Loyalty Info by XContactId
  /contact/hash:
    $ref: 'functions/getHashedXContactId.yaml'

  # Get Contact Activities
  /contact/activities:
    $ref: 'functions/getContactActivities.yaml'


  # Resource - Plans
  # Change Contact Loyalty Plan
  /contact/changeplans:
    $ref: 'functions/changeContactLoyaltyPlan.yaml'

  # Get Contact Loyalty Plans
  /contact/programSettings:
    $ref: 'functions/getProgramSettings.yaml'

  # Resource - Actions
  # Get Contact Actions
  /contact/actions:
    $ref: 'functions/getContactActions.yaml'

  # Resource - Tiers
  # Get Contact Tiers
  /contact/tiers:
    $ref: 'functions/getContactTiers.yaml'

  # Downgrade Contact Tier
  /contact/tiers/downgrade:
    $ref: 'functions/downgradeContactTiers.yaml'

  # Upgrade Contact Tier
  /contact/tiers/upgrade:
    $ref: 'functions/upgradeContactTiers.yaml'

components:
  schemas:
    resources:
      type: object
      required: [displayName, name, type, noDataExpression]
      properties:
        displayName:
          type: string
          enum: [Resource]
        name:
          type: string
          enum: [resource]
        type:
          type: string
          enum: [options]
        noDataExpression:
          type: boolean
          enum: [true]
        default:
          type: string
        options:
          type: array
          items:
            type: object
            required: [name, value]
            properties:
              name:
                type: string
              value:
                type: string
          enum:
          - { name: Contact, value: contact }
          - { name: Plans, value: plans }
          - { name: Actions, value: actions }
          - { name: Tiers, value: tiers }
