openapi: 3.0.0
info:
  title: Emarsys Loyalty API
  version: 1.0.0
paths:
  /api/v4/contact:
    delete:
      summary: deleteContact
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xInitiatedBy
          in: header
          required: false
          schema:
            type: string
      responses:
        '204':
          description: Contact deleted successfully
        '404':
          description: Contact not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                  errorMessage:
                    type: string
                example:
                  errorCode: 404
                  errorMessage: Contact not found
        '500':
          description: Generic error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                  errorMessage:
                    type: string
                example:
                  errorCode: 500
                  errorMessage: Internal server error

  /api/v4/contact/join:
    post:
      summary: addContact
      parameters:
        - name: withPointsAllocations
          in: query
          required: false
          schema:
            type: string
        - name: withTierExpiration
          in: query
          required: false
          schema:
            type: string
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xLanguage
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK

  /api/v4/contact/contact:
    get:
      summary: getContactLoyaltyInfo
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xPlanId
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK

  /api/v4/contact/hash:
    get:
      summary: getHashedXContactId
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK

  /api/v4/contact/activities:
    get:
      summary: getContactActivities
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xLanguage
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK

  /api/v4/contact/changeplan:
    put:
      summary: changeContactLoyaltyPlan
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xPlanId
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [balancePoints, pendingPoints, redeemedVouchers, statusPoints]
              properties:
                balancePoints:
                  type: integer
                pendingPoints:
                  type: integer
                redeemedVouchers:
                  type: integer
                statusPoints:
                  type: integer
      responses:
        '200':
          description: OK

  /api/v4/contact/programSettings:
    get:
      summary: getProgramSettings
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xCurrency
          in: header
          required: false
          schema:
            type: string
        - name: xLanguage
          in: header
          required: false
          schema:
            type: string
        - name: xMarket
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK

  /api/v4/contact/actions:
    get:
      summary: getContactActions
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xLanguage
          in: header
          required: false
          schema:
            type: string
        - name: xCurrency
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK

  /api/v4/contact/tiers:
    get:
      summary: getContactTiers
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xLanguage
          in: header
          required: false
          schema:
            type: string
        - name: xMarket
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK

  /api/v4/contact/tiers/downgrade:
    put:
      summary: downgradeContactTiers
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xExitTo
          in: header
          required: false
          schema:
            type: string
        - name: xReasonForTierChange
          in: header
          required: false
          schema:
            type: string
        - name: xTierId
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK

  /api/v4/contact/tiers/upgrade:
    put:
      summary: upgradeContactTiers
      parameters:
        - name: xContactId
          in: header
          required: true
          schema:
            type: string
        - name: xReasonForTierChange
          in: header
          required: false
          schema:
            type: string
        - name: xTierId
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
