title: n8n Resource Parameter
type: object
required: [displayName, name, type, noDataExpression]
properties:
  displayName:      { const: Resource }
  name:             { const: resource }
  type:             { const: options }
  noDataExpression: { const: true }
  default:
    type: string
  options:
    type: array
    items:
      type: object
      required: [name, value]
      properties:
        name:
          type: string
        value:
          type: string
      enum:
        - { name: Contact, value: contact }
        - { name: Plans, value: plans }
        - { name: Actions, value: actions }
        - { name: Tiers, value: tiers }

definitions:
  Option:
    type: object
    required: [name, value]
    properties:
      name:  { type: string }
      value: { type: string }
