openapi: 3.0.3
info:
  title: n8n Node Base Schemas
  version: 1.0.0
  description: Component-only specification for node-parameter definitions.
paths: {}
components:
  schemas:
    DisplayOptions:
      type: object
      properties:
        show:
          type: object
          properties:
            resource:
              type: array
              items:
                type: string
            operation:
              type: array
              items:
                type: string
          additionalProperties: false
    Option:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
        value:
          type: string
        action:
          type: string
        description:
          type: string
        routing:
          type: object
    Parameter:
      type: object
      required:
        - displayName
        - name
        - type
      properties:
        displayName:
          type: string
        name:
          type: string
        type:
          type: string
        noDataExpression:
          type: boolean
        placeholder:
          type: string
        default: {}
        displayOptions:
          $ref: '#/components/schemas/DisplayOptions'
        options:
          type: array
          items:
            $ref: '#/components/schemas/Option'
    OperationOption:
      allOf:
        - $ref: '#/components/schemas/Option'
    NodeBase:
      title: n8n Node Base Schema
      type: object
      required:
        - displayName
        - name
        - icon
        - group
        - description
        - defaults
        - inputs
        - outputs
        - credentials
        - requestDefaults
        - properties
      properties:
        displayName:
          type: string
        name:
          type: string
        icon:
          oneOf:
            - type: string
            - type: object
              required:
                - light
                - dark
              properties:
                light:
                  type: string
                dark:
                  type: string
        group:
          type: array
          items:
            type: string
            enum:
              - trigger
              - schedule
              - input
              - output
              - transform
              - ''
        description:
          type: string
        defaults:
          type: object
          required:
            - name
            - color
          properties:
            name:
              type: string
            color:
              type: string
              pattern: ^#[0-9A-Fa-f]{6}$
        forceInputNodeExecution:
          type: boolean
        inputs:
          type: array
          items:
            type: string
        outputs:
          type: array
          items:
            type: string
        requiredInputs:
          oneOf:
            - type: integer
            - type: array
              items:
                type: integer
        credentials:
          type: array
          items:
            type: object
            required:
              - name
              - required
            properties:
              name:
                type: string
              required:
                type: boolean
        requestDefaults:
          type: object
          required:
            - baseURL
          properties:
            baseURL:
              type: string
              format: uri
            headers:
              type: object
            url:
              type: string
        properties:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
    ResourceParameter:
      title: n8n Resource Parameter
      type: object
      required:
        - displayName
        - name
        - type
        - noDataExpression
      properties:
        displayName:
          type: string
          enum:
            - Resource
        name:
          type: string
          enum:
            - resource
        type:
          type: string
          enum:
            - options
        noDataExpression:
          type: boolean
          enum:
            - true
        default:
          type: string
        options:
          type: array
          items:
            $ref: '#/components/schemas/Option'
    OperationsParameter:
      title: n8n Operations Parameter
      type: object
      required:
        - displayName
        - name
        - type
        - noDataExpression
        - options
      properties:
        displayName:
          type: string
          enum:
            - Options
        name:
          type: string
          enum:
            - operation
        type:
          type: string
          enum:
            - options
        noDataExpression:
          type: boolean
          enum:
            - true
        options:
          type: array
          items:
            $ref: '#/components/schemas/OperationOption'
