get:
  summary: getContactLoyaltyInfo
  security: []
  tags:
    - contact
  description: Retrieve loyalty information for the contact specified by the xContactId header.
  operationId: getContactLoyaltyInfo

  parameters:
    - name: xContactId
      in: header
      required: true
      description: Unique identifier for the contact.
      schema:
        type: string
      example: abc123

    - name: xPlanId
      in: header
      required: false
      description: Plan ID to filter loyalty information by specific plan.
      schema:
        type: string
      example: plan789

  responses:
    '200':
      $ref: '../components/responses.yaml#/components/responses/responseGetContactLoyaltyInfo'
    '400':
      $ref: '../components/responses.yaml#/components/responses/ValidationErrorResponse'
    '404':
      $ref: '../components/responses.yaml#/components/responses/NotFoundErrorResponse'
    '500':
      $ref: '../components/responses.yaml#/components/responses/ServerErrorResponse'
