get:
  summary: getHashedXContactId
  security: []
  tags:
    - contact
  description: Retrieve the hashed version of the specified xContactId header value.

  parameters:
    - name: xContactId
      in: header
      required: true
      description: The contact ID to be hashed.
      schema:
        type: string
      example: abc123

  responses:
    '200':
      $ref: '../components/responses.yaml#/components/responses/responseGetHashedXContactId'
    '400':
      $ref: '../components/responses.yaml#/components/responses/ValidationErrorResponse'
    '404':
      $ref: '../components/responses.yaml#/components/responses/NotFoundErrorResponse'
    '500':
      $ref: '../components/responses.yaml#/components/responses/ServerErrorResponse'
