get:
  summary: getProgramSettings
  security: []
  tags:
    - plan
  description: Retrieve the program settings for the specified contact. Optionally accepts currency, language, and market headers to customize the response.
  operationId: getProgramSettings

  parameters:
    - name: xContactId
      in: header
      required: true
      description: Unique identifier of the contact.
      schema:
        type: string
      example: abc123

    - name: xCurrency
      in: header
      required: false
      description: Currency code used to localize program settings.
      schema:
        type: string
      example: JPY

    - name: xLanguage
      in: header
      required: false
      description: Preferred language for the response content.
      schema:
        type: string
      example: ja

    - name: xMarket
      in: header
      required: false
      description: Market context for the program settings.
      schema:
        type: string
      example: JP

  responses:
    '200':
      $ref: '../components/responses.yaml#/components/responses/responseGetProgramSettings'
    '400':
      $ref: '../components/responses.yaml#/components/responses/ValidationErrorResponse'
    '404':
      $ref: '../components/responses.yaml#/components/responses/NotFoundErrorResponse'
    '500':
      $ref: '../components/responses.yaml#/components/responses/ServerErrorResponse'
